#ifndef SHARE_STATIC_INCLUDE_H
#define SHARE_STATIC_INCLUDE_H

// QT LIBRARY
#include <QMainWindow>
#include <QtSvg/QSvgRenderer>
#include <QStringList>
#include <QJsonDocument>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QMainWindow>
#include <QWidget>
#include <QByteArray>
#include <QApplication>
#include <QLineEdit>
#include <QString>
#include <QStatusBar>
#include <QMenuBar>
#include <QMenu>
#include <QDragEnterEvent>
#include <QWebEngineView>
#include <QWebEnginePage>
#include <QWebEngineProfile>
#include <QWebEngineCookieStore>
#include <QDesktopWidget>
#include <QMessageBox>
#include <QSharedData>
#include <QDebug>
#include <QShortcut>
#include <QtGui>
#include <QMenu>
#include <QFontDialog>
#include <QColorDialog>
#include <QToolButton>
#include <QPixmap>
#include <QPushButton>
#include <QLineEdit>
#include <QComboBox>
#include <QSplitter>
#include <QSplitterHandle>
#include <QString>
#include <QVariant>
#include <QDebug>
#include <QHeaderView>
#include <QModelIndex>
#include <QTableView>
#include <QDateTimeEdit>
#include <QStandardItemModel>
#include <QTableWidget>
#include <QTableWidgetItem>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QGridLayout>
#include <QEvent>
#include <QKeyEvent>
#include <QList>
#include <QStandardItemModel>
#include <QTreeWidget>
#include <QTreeWidgetItem>
#include <QListWidget>
#include <QStringList>
#include <QTextEdit>
#include <QTextDocument>
#include <QTimer>
#include <QCloseEvent>
#include <QHideEvent>
#include <QShowEvent>
#include <QMouseEvent>
#include <QFormLayout>
#include <QDate>
#include <QScrollBar>
#include <QHeaderView>
#include <QCompleter>
#include <QFrame>
#include <QTime>
#include <QTimer>
#include <QObject>
#include <QPrinter>
#include <QPrinterInfo>
#include <QPrintDialog>
#include <QPainter>
#include <QFile>
#include <QFileDialog>
#include <QLabel>
#include <QItemDelegate>
#include <QCheckBox>
#include <QStylePainter>
#include <QGraphicsScene>
#include <QGraphicsView>
#include <QGraphicsPixmapItem>
#include <QGuiApplication>
#include <QDoubleSpinBox>
#include <QProcess>
#include <QList>
#include <QHostInfo>
#include <QNetworkInterface>
#include <QKeyEvent>
#include <QAbstractItemView>
#include <QtMath>

// STD LIBRARY
#include <cassert>
#include <iostream>
#include <typeinfo>
#include <cinttypes>
#include <utility>
#include <list>
#include <set>
#include <algorithm>
#endif // SHARE_STATIC_INCLUDE_H
